spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/safeharbordb?createDatabaseIfNotExist=true
spring.datasource.username=root1
spring.datasource.password=Vickybujji45
spring.security.user.name=admin
spring.security.user.password=chii@04
spring.security.user.roles=ADMIN
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080
